#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# zsh, aliases and function
rm -rf "$HOME/.zshrc"
ln -s "$DOTFILES/zsh/zshrc" "$HOME/.zshrc"

rm -rf "$HOME/.zsh_aliases"
ln -s "$DOTFILES/zsh/aliases.zsh" "$HOME/.zsh_aliases"

rm -rf "$HOME/.zsh_functions"
ln -s "$DOTFILES/zsh/functions.zsh" "$HOME/.zsh_functions"

# kitty
rm -rf "$HOME/.config/kitty"
ln -s "$DOTFILES/kitty" "$HOME/.config/kitty"

# tmux
rm -rf "$HOME/.tmux.conf"
ln -s "$DOTFILES/tmux/tmux.conf" "$HOME/.tmux.conf"

# scripts
mkdir -p "$HOME/.local/bin"

rm -rf "$HOME/.local/bin/t"
ln -s "$DOTFILES/scripts/t" "$HOME/.local/bin/t"

rm -rf "$HOME/.local/bin/tmux-sessionizer"
ln -s "$DOTFILES/scripts/tmux-sessionizer" "$HOME/.local/bin/tmux-sessionizer"

# nvim
rm -rf "$HOME/.config/nvim/lua"
ln -s "$DOTFILES/nvim/lua" "$HOME/.config/nvim/lua"

# notes
rm -rf "$HOME/.config/notes/config"
ln -s "$DOTFILES/notes/config" "$HOME/.config/notes/config"

# karabiner
rm -rf "$HOME/.config/karabiner/karabiner.json"
ln -s "$DOTFILES/karabiner/karabiner.json" "$HOME/.config/karabiner/karabiner.json"

# skhd
rm -rf "$HOME/.config/skhd/skhdrc"
ln -s "$DOTFILES/skhd/skhdrc" "$HOME/.config/skhd/skhdrc"

# yabai
rm -rf "$HOME/.config/yabai/yabairc"
ln -s "$DOTFILES/yabai/yabairc" "$HOME/.config/yabai/yabairc"

