#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf "$HOME/.zshrc"
ln -s "$DOTFILES/zsh/zshrc" "$HOME/.zshrc"

rm -rf "$HOME/.zsh_aliases"
ln -s "$DOTFILES/zsh/aliases.zsh" "$HOME/.zsh_aliases"

rm -rf "$HOME/.zsh_functions"
ln -s "$DOTFILES/zsh/functions.zsh" "$HOME/.zsh_functions"

rm -rf "$HOME/.config/kitty"
ln -s "$DOTFILES/kitty" "$HOME/.config/kitty"

rm -rf "$HOME/.tmux.conf"
ln -s "$DOTFILES/tmux/tmux.conf" "$HOME/.tmux.conf"

mkdir -p "$HOME/.local/bin"

rm -rf "$HOME/.local/bin/t"
ln -s "$DOTFILES/scripts/t" "$HOME/.local/bin/t"

rm -rf "$HOME/.local/bin/tmux-sessionizer"
ln -s "$DOTFILES/scripts/tmux-sessionizer" "$HOME/.local/bin/tmux-sessionizer"

rm -rf "$HOME/.config/nvim/lua"
ln -s "$DOTFILES/nvim/lua" "$HOME/.config/nvim/lua"

rm -rf "$HOME/.config/notes/config"
ln -s "$DOTFILES/notes/config" "$HOME/.config/notes/config"
